- name: Create secret for kiali in namespace {{ ns_name }}
  template:
    src: 'templates/secret.yml'
    dest: "{{role_path}}/../../output/kiali-secret.yml"

- name: aply secrets for kiali in namespace {{ ns_name }}
  shell: "kubectl apply -f {{role_path}}/../../output/kiali-secret.yml"

