# Delete a namespace if it exist
# The name of the namespace to be deleted is given in variable ns_name

- name: Check if namespace exists
  shell: "kubectl get namespace/{{ ns_name }}"
  ignore_errors: true
  register: r

- name: Delete namespace {{ ns_name }}
  shell: "kubectl delete namespace {{ ns_name }}"
  when:
    - r.rc == 0

