apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: {{ns_name}}
  labels:
    app: kiali
type: Opaque
data:
  username: {{KIALI_USERNAME | b64encode}}
  passphrase: {{KIALI_PASSWORD | b64encode}}

